### ISSUE TITLE
winfoom

### ISSUE THREAD

**Issue by barroudjo** [ecovaci/foom#2]
Hello,
Sorry I know it's not the place to do it, but I was wondering why you removed your winfoom repo ? It's a great tool, I'm using it everyday, and it's too bad that other people won't find it now !

**Comment by ecovaci** [comment]
Hello,
To be honest with you, the main reason I remove it is the low rating it got after more than one year since the first release: only 55 stars, even though it had about 3000 downloads. What I get from here is either people who download it were massively dissatisfied with the application or they were too lazy to make a Github account. The second reason is that the decision to support almost all proxy mechanisms (NTLM, Kerberos, PAC, Direct) was IMO a mistake. Some parts of Winfoom application do not coexist harmoniously together at architecture level, even though the application run just fine. 
As far as I'm concerned Winfoom is dead and buried, I'll never work on it and I do not recommend using an application that is not maintained anymore .
Anyway, thank you for your kind words, the only ones I received for working on Winfoom. 
I wish you all the best!

**Comment by barroudjo** [comment]
I think you're reading too much into the star rating vs number of downloads, I can tell you that the people in my organisation are extremely happy to have it, and that's quite a lot of people... If you still had your repo I'd tell them to star it ;-).

**Comment by ecovaci** [comment]
The star rating gives me a valuable feedback, other than that I don't care about rating.
I'm working on another open sourced project called myakon, sort of winfoom stripped of Kerberos, PAC, Direct proxy support, such that on Windows will support all proxy  protocols for the current user and for non-Windows systems only NTLM. Also, no GUI will be provided.
Hopefully this one will have a clean architecture with good test coverage.

**Comment by barroudjo** [comment]
Sounds good !

**Comment by ecovaci** [comment]
Hello,
I have just release a new version of [Winfoom](https://github.com/ecovaci/winfoom)
Please check it out and provide a feedback.
Thank you

**Comment by barroudjo** [comment]
Thanks, I'll take a look at it !
